class ProjectIdeasController < ApplicationController
  before_action :set_project_idea, only: [:show, :destroy]

  def index
    inventory = current_user.gift_inventory
    @project_ideas = inventory ? inventory.project_ideas.ordered : ProjectIdea.none
  end

  def show; end

  def destroy
    @project_idea.destroy
    redirect_back fallback_location: project_ideas_path, notice: "Project removed."
  end

  def download
    inventory = current_user.gift_inventory
    ideas     = inventory ? inventory.project_ideas.ordered : ProjectIdea.none
    send_data ideas_to_markdown(ideas),
              filename:    "capacitymap-projects.md",
              type:        "text/markdown",
              disposition: "attachment"
  end

  private

  def set_project_idea
    inventory       = current_user.gift_inventory
    @project_idea   = inventory&.project_ideas&.find_by(id: params[:id])
    render file: Rails.public_path.join("404.html"), status: :not_found unless @project_idea
  end

  def ideas_to_markdown(ideas)
    app_name = ENV.fetch("APP_NAME", "CapacityMap Demo")
    lines    = ["# My Gift Inventory Projects\n", "_Generated by #{app_name}_\n\n---\n"]

    ideas.each_with_index do |idea, i|
      lines << "\n## #{i + 1}. #{idea.name}\n\n"
      lines << "**Impact type:** #{idea.impact_type}  \n" if idea.impact_type.present?
      lines << "**Time commitment:** #{idea.time_commitment}\n\n" if idea.time_commitment.present?
      lines << "#{idea.description}\n"

      if idea.gifts_used_list.any?
        lines << "\n**Gifts this draws on:**\n"
        idea.gifts_used_list.each do |gift|
          category = gift["category"].to_s.tr("_", " ").capitalize
          lines << "- #{category}: #{gift['name']}\n"
        end
      end

      lines << "\n**First step this week:** #{idea.first_step}\n" if idea.first_step.present?
      lines << "\n---\n"
    end

    lines.join
  end
end
